//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPR_Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPR_Tasks()
        {
            this.SPR_Trigger_Daily = new HashSet<SPR_Trigger_Daily>();
            this.SPR_Trigger_Monthly = new HashSet<SPR_Trigger_Monthly>();
            this.SPR_Trigger_Once = new HashSet<SPR_Trigger_Once>();
            this.SPR_Trigger_Weekly = new HashSet<SPR_Trigger_Weekly>();
        }
    
        public long ID { get; set; }
        public long ReportID { get; set; }
        public string Name { get; set; }
    
        public virtual SPR_Reports SPR_Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPR_Trigger_Daily> SPR_Trigger_Daily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPR_Trigger_Monthly> SPR_Trigger_Monthly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPR_Trigger_Once> SPR_Trigger_Once { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPR_Trigger_Weekly> SPR_Trigger_Weekly { get; set; }
    }
}
