//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class csdbEntities : DbContext
    {
        public csdbEntities()
            : base("name=csdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SPR_DataFeed> SPR_DataFeed { get; set; }
        public virtual DbSet<SPR_ReportAssets> SPR_ReportAssets { get; set; }
        public virtual DbSet<SPR_Reports> SPR_Reports { get; set; }
        public virtual DbSet<SPR_ReportSettings> SPR_ReportSettings { get; set; }
        public virtual DbSet<SPR_Tasks> SPR_Tasks { get; set; }
        public virtual DbSet<SPR_Trigger_Daily> SPR_Trigger_Daily { get; set; }
        public virtual DbSet<SPR_Trigger_Monthly> SPR_Trigger_Monthly { get; set; }
        public virtual DbSet<SPR_Trigger_Once> SPR_Trigger_Once { get; set; }
        public virtual DbSet<SPR_Trigger_Weekly> SPR_Trigger_Weekly { get; set; }
    }
}
